### ISSUE TITLE
Neues Beispielissue

### ISSUE THREAD

**Issue by Semigroup** [Semigroup/Werwolf#27]
Things gonna happen here

**Comment by Semigroup** [comment]
I agree, I agree

**Comment by Semigroup** [comment]
Look at all the shiny labels
he even assigned himself

**Comment by Semigroup** [comment]
Look: Markup Formatting:
- [ ] Item 1
- [x] Item 2
- [ ] Item 3

**Comment by Semigroup** [comment]
1. 
2.
3.

**Comment by Xezarior** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yirZdxPq&#x2F;1-beispielwolf"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Beispielwolf</a>
