### ISSUE TITLE
.sln file

### ISSUE THREAD

**Issue by dMoelishR** [Semigroup/Werwolf#33]
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

The officil github/gitignore file for VisuaStudio doesn't ignore the .sln file. But this project does!
I have to create my own file and import everything, very nasty!

Please take out *.sln of your .gitignore.

**Comment by Semigroup** [comment]
Hey Moe
habe die .sln und .csproj jetzt wieder rein gemacht
Grund fürs Rausschmeißen war, dass bei einem anderen ich mal massive Probleme mit Github auf zwei Laptops hatte, weil die Files da keine relativen Pfade angaben, und ich so immer per Hand die jeweilige *.sln bzw. *.csproj korrigieren musste, was eine ziemliche Drecksarbeit war.

Du dürftest das Programm aber ohnehin nicht kompilieren können, weil du Assistment nicht benutzen kannst, weil da auch noch ein paar Daten fehlen, aber darum kümmere ich mich später.

Hab übrigens gar nicht gewusst, dass jedermann hier auf meinem Issuetracker rumkommentieren darf :)
